---


- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes

- name: add docker GPG key for ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository for ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
    state: present

- name: install docker on ubuntu
  apt:
    name: docker-ce
    state: present

- name: adding users to group docker
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Generate Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: build and start docker compose services on ubuntu
  command: docker compose up --build -d
  args:
    chdir: /home/{{ ansible_user }}/repos
